apiVersion: apps/v1
kind: Deployment
metadata:
  name: php7-4-imap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php7-4-imap
  template:
    metadata:
      labels:
        app: php7-4-imap
    spec:
      containers:
      - image: quay.io/xm0uray/quay_ad_11_vvn_img_docker_v1
        name: php7-4-imap

---

apiVersion: v1
kind: Service
metadata:
  name: php7-4-imap
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "hello-world"
    port: 6080
  selector:
    app: php7-4-imap
