apiVersion: apps/v1
kind: Deployment
metadata:
  name: php7-4-imap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php7-4-imap
  template:
    metadata:
      labels:
        app: php7-4-imap
    spec:
      containers:
      - image: okteto/hello-world:golang
        name: php7-4-imap

---

apiVersion: v1
kind: Service
metadata:
  name: php7-4-imap
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "php7-4-imap"
    port: 8080
  selector:
    app: php7-4-imap
